### ISSUE TITLE
Possible bug when using blueprint model create

### ISSUE THREAD

**Issue by cotz1995** [onehilltech/blueprint-cli#7]
This might be be due to my own ignorance, but when I using the cli to create a new model it used blueprint.schma (which seemed to me to cause a callback already called error), but when I created them using the tutorial in the readme it said to use blueprint-mongodb.Schema. Making this change corrected the error. See code below for example:

Auto generated code that throws the error:
```
'use strict';

var blueprint = require ('blueprint')
  , Schema = blueprint.Schema
  ;

var schema = new Schema ({
  // add fields here
});

const COLLECTION_NAME = 'example';
module.exports = blueprint.model (COLLECTION_NAME, schema);

```

Working code created as described in readme:

``` 
'use strict';

var mongodb = require ('@onehilltech/blueprint-mongodb')
    ;

var schema = new mongodb.Schema({
  // add fields here
});

const COLLECTION_NAME = 'example';
module.exports = mongodb.model (COLLECTION_NAME, schema);

```

**Comment by hilljh82** [comment]
Please install the latest version of blueprint-cli.
